# Dhan API Credentials
dhan_client_id=
dhan_access_token=
dhan_stock_data_url=https://images.dhan.co/api-data/api-scrip-master.csv

fyers_client_id=
fyers_secret_key=
fyers_redirect_uri=

#timeframe D=daily, W=Weekly
timeframe=W
no_of_days=1826
